name = "cicek-crm"
main = "src/worker.ts"
compatibility_date = "2024-02-12"

[[d1_databases]]
binding = "DB"
database_name = "cicek-crm-db"
database_id = "4b0bbc33-f9ec-4adf-a983-d6683839752d"

[site]
bucket = "./public"

[build]
command = "npm install && npm run build"

[routes]
/api/* = "/api/*"
/* = "/public/*"

[env.development]
name = "cicek-crm-dev"
