name = "cicek-crm-api"
main = "src/worker.ts"
compatibility_date = "2024-02-12"

[[d1_databases]]
binding = "DB"
database_name = "cicek-crm-db"
database_id = "4b0bbc33-f9ec-4adf-a983-d6683839752d"

# Worker'ı Pages ile entegre et
[triggers]
pages = [
  { pattern = "cicekcrm.pages.dev", custom_domain = true }
]

[[routes]]
pattern = "cicekcrm.pages.dev/api/*"
zone_name = "pages.dev"

[site]
bucket = "./public"

[build]
command = "npm run build"
