name = "cicek-crm-api"
main = "worker.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "cicek-crm-db"
database_id = "4b0bbc33-f9ec-4adf-a983-d6683839752d"

[env.development]
workers_dev = true

[env.production]
routes = [
  { pattern = "api.cicekcrm.com", custom_domain = true }
]
